#!/bin/bash
# Creates tvm_ffi_binding stubs for xgrammar during cross-compilation.
# Normally these are auto-generated by loading the compiled library via ctypes,
# which is impossible when cross-compiling (can't load arm64 lib on x86_64 host).
# The stubs simply register FFI functions at runtime via init_ffi_api.
set -euo pipefail

B=$SP_DIR/xgrammar/tvm_ffi_binding
mkdir -p $B/kernels $B/testing/grammar_functor

I='from tvm_ffi.registry import init_ffi_api as _FFI_INIT_FUNC'

touch $B/__init__.py $B/kernels/__init__.py $B/testing/__init__.py $B/testing/grammar_functor/__init__.py

printf '%s\n' "$I" '_FFI_INIT_FUNC("xgrammar", __name__)' > $B/_ffi_api.py
printf '%s\n' "$I" '_FFI_INIT_FUNC("xgrammar.config", __name__)' > $B/config.py
printf '%s\n' "$I" '_FFI_INIT_FUNC("xgrammar.kernels", __name__)' > $B/kernels/_ffi_api.py
printf '%s\n' "$I" '_FFI_INIT_FUNC("xgrammar.testing", __name__)' > $B/testing/_ffi_api.py
printf '%s\n' "$I" '_FFI_INIT_FUNC("xgrammar.testing.grammar_functor", __name__)' > $B/testing/grammar_functor/_ffi_api.py
