context:
  name: xgrammar
  version: "0.1.13"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/mlc-ai/xgrammar/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 0a3abfed7d491226a6f5ef2bd8e5a01516eff87dbef5898b1ae517c523c764c4
  patches:
    - 001-fix-macos-no-triton.patch

build:
  number: 0
  skip:
    - win # xgrammar claims windows support but it's very broken
  script: |
    mkdir -p build
    cd build
    export CXXFLAGS="$CXXFLAGS -isystem $PREFIX/include"
    if [[ $(uname) == "Linux" ]]; then
      export CXXFLAGS="$CXXFLAGS -Wno-dangling-reference"
    fi
    cmake ${CMAKE_ARGS} .. -G Ninja
    ninja
    cd ../python
    ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    # TODO: cross-compiling for Linux aarch64 is broken but works for m1
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - pybind11
        - setuptools
        - dlpack
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - dlpack
    - pybind11
    - python
    - cmake
    - pip
    - setuptools
  run:
    - if: linux
      then:
        - triton
    - pydantic
    - python
    - sentencepiece
    - tiktoken
    - pytorch
    - transformers
    - pytest

tests:
  - python:
      imports:
        - xgrammar
      pip_check: true

about:
  homepage: https://github.com/mlc-ai/xgrammar
  summary: XGrammar is an open-source library for efficient, flexible, and portable structured generation.
  license: Apache-2.0 AND BSD-4-Clause
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - zbowling
