schema_version: 1

context:
  name: xgrammar
  version: 0.1.14

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/xgrammar-${{ version }}.tar.gz
  sha256: b0d11ee9d10a9812f2b646a40b149e8ead88251ff1f3cac2709efd31882176f2

build:
  number: 0
  script: |
    export CXXFLAGS="$CXXFLAGS -isystem $PREFIX/include"
    if [[ $(uname) == "Linux" ]]; then
      export CXXFLAGS="$CXXFLAGS -Wno-dangling-reference"
    fi
    ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then:
      - python
      - cross-python_${{ target_platform }}
      - pybind11
      - scikit-build-core >=0.10.0
      - dlpack
      - pytest
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - python
    - scikit-build-core >=0.10.0
    - pybind11 >=2.11.0
    - pip
    - dlpack
    - pytest
  run:
    - python
    - pydantic
    - sentencepiece
    - tiktoken
    - pytorch >=1.10.0
    - transformers >=4.38.0
    - if: linux
      then: triton

tests:
  - python:
      imports:
        - xgrammar
      pip_check: true

about:
  homepage: https://github.com/mlc-ai/xgrammar
  summary: XGrammar is an open-source library for efficient, flexible, and portable structured generation.
  license: Apache-2.0 AND BSD-4-Clause
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - zbowling
