conda_build_tool: rattler-build
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
build_platform:
  linux_aarch64: linux_aarch64
  linux_ppc64le: linux_ppc64le
  osx_arm64: osx_64
provider:
  linux_ppc64le: default
  linux_aarch64: default
test: native_and_emulated
